name: Telegram Live Stream

on:
  workflow_dispatch: # මුලින්ම අතින් start කරන්න
  workflow_run:
    workflows: ["Telegram Live Stream"] # මෙතන තියෙන නම 'name' එකට සමාන විය යුතුයි
    types:
      - completed # කලින් එක ඉවර වුණ ගමන් මේක වැඩ කරයි

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
          M3U8_URL: ${{ secrets.M3U8_URL }}
        run: |
          ffmpeg -re -i "$M3U8_URL" \
          -vf "split[v1][v2];[v1]scale=480:854:force_original_aspect_ratio=increase,crop=480:854,boxblur=10:5[bg];[v2]scale=480:-1[fg];[bg][fg]overlay=(W-w)/2:(H-h)/2" \
          -c:v libx264 -preset ultrafast -b:v 2000k -maxrate 2000k -bufsize 4000k \
          -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k \
          -f flv "$RTMP_URL"
          
