name: Streamer

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Starter"]
    types: [completed]

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg
      - name: Streaming
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
          M3U8_URL: ${{ secrets.M3U8_URL }}
        run: |
          ffmpeg -re -i "$M3U8_URL" -vf "scale=480:854" -c:v libx264 -preset ultrafast -b:v 2000k -f flv "$RTMP_URL"
          
